language: node_js
node_js:
  - '12.0'
  - '4'
sudo: required
script:
    - "npm run test-cov"
after_script: "npm install coveralls && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage"